import type { Metadata } from 'next';
import { Livvic } from 'next/font/google';
import './globals.css';

const livvic = Livvic({
	variable: '--font-livvic',
	subsets: ['latin'],
	weight: ['600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${livvic.variable} `}>{children}</body>
		</html>
	);
}
